# Generated by Django 4.1.7 on 2023-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
